# Generated by Django 2.0 on 2018-01-02 21:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerol',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None),
        ),
    ]
