# Generated by Django 2.0 on 2018-01-09 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('request_by', models.CharField(max_length=200)),
                ('executed_by', models.CharField(max_length=200)),
                ('justification', models.TextField()),
                ('planned_start', models.DateField()),
                ('planned_completion', models.DateField()),
                ('started_on', models.DateField()),
                ('finished_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('changes', models.TextField()),
                ('participants', models.TextField()),
                ('affected_items', models.ManyToManyField(to='catalogs.Item')),
                ('affected_services', models.ManyToManyField(to='catalogs.Service')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Change')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('notified_by', models.CharField(max_length=100)),
                ('incident_description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('participants', models.TextField()),
                ('affected_items', models.ManyToManyField(to='catalogs.Item')),
                ('affected_services', models.ManyToManyField(to='catalogs.Service')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Change')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnownErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kerror_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kerror_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('planned_start', models.DateField()),
                ('planned_completion', models.DateField()),
                ('started_on', models.DateField()),
                ('finished_on', models.DateField(blank=True, null=True)),
                ('change_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.ChangeStatus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('participants', models.TextField()),
                ('affected_items', models.ManyToManyField(to='catalogs.Item')),
                ('affected_services', models.ManyToManyField(to='catalogs.Service')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.TaskType'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Severity'),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='change',
            name='change_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.ChangeStatus'),
        ),
        migrations.AddField(
            model_name='change',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='change',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
