# Generated by Django 2.0 on 2018-01-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20180116_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Estados de incidentes',
                'verbose_name': 'Estado de incidente',
            },
        ),
        migrations.AlterModelOptions(
            name='change',
            options={'verbose_name': 'Cambio', 'verbose_name_plural': 'Cambios'},
        ),
        migrations.AlterModelOptions(
            name='changeentry',
            options={'verbose_name': 'Entrada de cambio', 'verbose_name_plural': 'Entradas de cambios'},
        ),
        migrations.AlterModelOptions(
            name='changestatus',
            options={'verbose_name': 'Estado de cambio', 'verbose_name_plural': 'Estados de cambio'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': 'Incidente', 'verbose_name_plural': 'Incidentes'},
        ),
        migrations.AlterModelOptions(
            name='incidentcategory',
            options={'verbose_name': 'Categoria de incidente', 'verbose_name_plural': 'Categorias de incidentes'},
        ),
        migrations.AlterModelOptions(
            name='incidententry',
            options={'verbose_name': 'Entrada de incidente', 'verbose_name_plural': 'Entradas de incidentes'},
        ),
        migrations.AlterModelOptions(
            name='knownerrors',
            options={'verbose_name': 'Error conocido', 'verbose_name_plural': 'Errores Conocidos'},
        ),
        migrations.AlterModelOptions(
            name='severity',
            options={'verbose_name': 'Serveridad', 'verbose_name_plural': 'Serveridad de incidentes'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.AlterModelOptions(
            name='taskentry',
            options={'verbose_name': 'Entrada de trabajo', 'verbose_name_plural': 'Entradas de trabajos'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name': 'Tipo de tarea', 'verbose_name_plural': 'Tipos de tareas'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='change_status',
            new_name='task_status',
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='operations.IncidentStatus'),
            preserve_default=False,
        ),
    ]
