# Generated by Django 2.0 on 2018-01-18 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_incidentsource_incidentsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='operations.IncidentSource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='operations.IncidentSubcategory'),
            preserve_default=False,
        ),
    ]
