# Generated by Django 2.0 on 2018-01-18 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20180117_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentsubcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='operations.IncidentCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidentsubcategory',
            name='description',
            field=models.CharField(default='S/D', max_length=200),
        ),
    ]
