# Generated by Django 2.0 on 2018-01-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20180117_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severity',
            name='description',
            field=models.CharField(default='S/D', max_length=200),
        ),
    ]
