# Generated by Django 2.0 on 2018-01-20 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20180117_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidententry',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Incident'),
        ),
    ]
