# Generated by Django 2.0 on 2018-01-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20180119_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidententry',
            name='affected_items',
            field=models.ManyToManyField(blank=True, null=True, to='catalogs.Item'),
        ),
        migrations.AlterField(
            model_name='incidententry',
            name='affected_services',
            field=models.ManyToManyField(blank=True, null=True, to='catalogs.Service'),
        ),
    ]
