# Generated by Django 2.0 on 2018-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_auto_20180129_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidententry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrada de incidente', 'verbose_name_plural': 'Entradas de incidentes'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
