# Generated by Django 2.0 on 2018-02-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_auto_20180211_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskentry',
            name='participants',
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='affected_items',
            field=models.ManyToManyField(blank=True, null=True, to='catalogs.Item'),
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='affected_services',
            field=models.ManyToManyField(blank=True, null=True, to='catalogs.Service'),
        ),
    ]
