# Generated by Django 2.0 on 2018-02-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_auto_20180213_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeentry',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_entries', to='operations.Change'),
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='affected_items',
            field=models.ManyToManyField(blank=True, to='catalogs.Item'),
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='affected_services',
            field=models.ManyToManyField(blank=True, to='catalogs.Service'),
        ),
    ]
