# Generated by Django 2.0 on 2018-02-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_auto_20180215_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeentry',
            name='participants',
        ),
    ]
