# Generated by Django 2.0 on 2018-02-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_remove_changeentry_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changeentry',
            name='affected_items',
            field=models.ManyToManyField(blank=True, to='catalogs.Item'),
        ),
        migrations.AlterField(
            model_name='changeentry',
            name='affected_services',
            field=models.ManyToManyField(blank=True, to='catalogs.Service'),
        ),
    ]
